---
title: "BIO data - obecná zpracování"
subtitle: "BIOLIB slovniky | Ohrozeni"
author: "Katerina Krizova"
date: "2023-02-08"
output:
  pdf_document
    toc: true
    toc_depth: 2
    number_sections: false
    fig_caption: true
  fontsize: 11pt
  geometry: margin=1in

---

\newpage 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message=FALSE, fig.dim = c(8, 4))

# PACKAGES

# install.packages("tidyverse", dependencies = T)
# install.packages("readxl")
# install.packages("stringr")
# install.packages("mdbr")
# install.packages("RODBC")
# install.packages("odbc")
require(tidyverse)
require(readxl)
require(xlsx)
require(stringr) # ::str_split_fixed
require(RODBC) # ::read_mdb
require(odbc) # ::read_mdb

```

\newpage 

# PROJEKT A CESTY

```{r PROJECT SPECIFICATIONS AND PATHS}

# *** SWITCH *** SWITCH *** SWITCH *** SWITCH *** SWITCH ***

# slovnik <- "animalia"
# slovnik <- "fungi"
# slovnik <- "plantae"

# *** SWITCH *** SWITCH *** SWITCH *** SWITCH *** SWITCH ***

path <-  "C:/Users/krizova/Documents/R/"

path_bio <-  "M:/02 dokumenty/03 migrace/BIO/" # obecna slozka s biologickymi daty

```


# B I O L I B   S L O V N I K Y

## Pripojeni databaze 

```{r SET DATABASE CONNECTION}

dbname <- paste0(path_mdb, "bio_slovniky.accdb") # path to database
con <- RODBC::odbcConnectAccess2007(dbname)      # set the connection

# RODBC::sqlTables(con)                           # list tables in database

```

\newpage

## Nacteni tabulek

```{r READ AND MODIFY DB TABLES, warning = F}

if(slovnik == "animalia"){
  kmen <- RODBC::sqlFetch(con, "PRM_BioLib_080_Animalia_Kmen")  
  trida <- RODBC::sqlFetch(con, "PRM_BioLib_090_Animalia_Trida")  
  rad <- RODBC::sqlFetch(con, "PRM_BioLib_100_Animalia_Rad")  
  celed <- RODBC::sqlFetch(con, "PRM_BioLib_110_Animalia_Celed")  
  rod <- RODBC::sqlFetch(con, "PRM_BioLib_130_Animalia_Rod")  
  druh <- RODBC::sqlFetch(con, "PRM_BioLib_150_Animalia_Druh")  
  poddruh <- RODBC::sqlFetch(con, "PRM_BioLib_153_Animalia_Poddruh") 
} else if(slovnik == "fungi"){
  kmen <- RODBC::sqlFetch(con, "PRM_BioLib_080_Fungi_Kmen")  
  trida <- RODBC::sqlFetch(con, "PRM_BioLib_090_Fungi_Trida")  
  rad <- RODBC::sqlFetch(con, "PRM_BioLib_100_Fungi_Rad")  
  celed <- RODBC::sqlFetch(con, "PRM_BioLib_110_Fungi_Celed")  
  rod <- RODBC::sqlFetch(con, "PRM_BioLib_130_Fungi_Rod")  
  druh <- RODBC::sqlFetch(con, "PRM_BioLib_150_Fungi_Druh")  
  poddruh <- RODBC::sqlFetch(con, "PRM_BioLib_153_Fungi_Poddruh")
} else if(slovnik == "plantae"){
  kmen <- RODBC::sqlFetch(con, "PRM_BioLib_080_Plantae_Kmen")  
  trida <- RODBC::sqlFetch(con, "PRM_BioLib_090_Plantae_Trida")  
  rad <- RODBC::sqlFetch(con, "PRM_BioLib_100_Plantae_Rad")  
  celed <- RODBC::sqlFetch(con, "PRM_BioLib_110_Plantae_Celed")  
  rod <- RODBC::sqlFetch(con, "PRM_BioLib_130_Plantae_Rod")  
  druh <- RODBC::sqlFetch(con, "PRM_BioLib_150_Plantae_Druh")  
  poddruh <- RODBC::sqlFetch(con, "PRM_BioLib_153_Plantae_Poddruh")
} else print("I have a bad feeling about this!")

```

## Sloucit do jedne tabulky

```{r KINGDOM-SPECIFIC}

# add taxon prefix to column names

colnames(kmen) <- paste0("kmen_", colnames(kmen))
colnames(trida) <- paste0("trida_", colnames(trida))
colnames(rad) <- paste0("rad_", colnames(rad))
colnames(celed) <- paste0("celed_", colnames(celed))
colnames(rod) <- paste0("rod_", colnames(rod))
colnames(druh) <- paste0("druh_", colnames(druh))
colnames(poddruh) <- paste0("poddruh_", colnames(poddruh))


# full_join - this setup gives a full table WITH ALL and ORDERED COLUMNS

join1 <- full_join(kmen, trida, by = c("kmen_Nomen" = "trida_NadNomen"), 
                   keep = T, multiple = "any") # 111
join2 <- full_join(join1, rad, by = c("trida_Nomen" = "rad_NadNomen"), 
                   keep = T, multiple = "any") # 605
join3 <- full_join(join2, celed, by = c("rad_Nomen" = "celed_NadNomen"), 
                   keep = T, multiple = "any") # 6 569
join4 <- full_join(join3, rod, by = c("celed_Nomen" = "rod_NadNomen"), 
                   keep = T, multiple = "any") # 23 970
join5 <- full_join(join4, druh,by = c("rod_Nomen" = "druh_NadNomen"), 
                   keep = T, multiple = "any") # 108 313
join6 <- full_join(join5, poddruh, by = c("druh_Nomen" = "poddruh_NadNomen"), 
                   keep = T, multiple = "any") # 128 848


write.table(join6, paste0(path, "bioslov/BioLib_KKsummary_", slovnik, ".csv"), sep = ";", row.names = F)

```

### Mechorosty

```{r PATH}

projekt <- "MUZBE"

path <-  "C:/Users/krizova/Documents/R/"

path_data <-  paste0(path, "data/")
path_csv <-  paste0(path, "mus_csv/", projekt, "/")

path_muzbe <-  "M:/03 klienti/kraj moravskoslezsky/muzeum beskyd - MUZBE/" # databaze

```

com = ceske ekvivalenty  
tax = strom latinsky  
ton = com (?)  

```{r O ZICHA BIOLIB DATA}

com <- read.table(paste0(path_data, projekt, "/ComName.csv"), 
                   sep = ";", header = T, fileEncoding="cp1250")
tax <- read.table(paste0(path_data, projekt, "/TaxName.csv"), 
                   sep = ";", header = T, fileEncoding="cp1250")
ton <- read.table(paste0(path_data, projekt, "/Taxon.csv"), 
                   sep = ";", header = T, fileEncoding="cp1250")

# prideleni kategorii jednotlivym nazvum

tax_modif <- tax %>% 
  mutate(tn_name = str_trim(tn_name),
         MLEVEL = case_when(str_detect(tn_name, "\\ssubsp\\.|\\svar\\.|\\sf\\.|\\sß") ~ "poddruh",  
                            str_detect(tn_name, "^\\w+\\s\\w+$")|str_detect(tn_name, "-|\\?") ~ "druh", 
                            str_detect(tn_name, "\\ssubgen\\.|\\ssect\\.") ~ "rod",  
                            str_detect(tn_name, "^\\w+ae$") ~ "celed",  
                            str_detect(tn_name, "^\\w+ales$") ~ "rad",  
                            str_detect(tn_name, "^\\w+psida$") ~ "trida",  
                            str_detect(tn_name, "^\\w+phyta$") ~ "oddeleni", 
                            # str_detect(tn_name, "\\?") ~ "nejasne",  
                            TRUE ~ "jine"),
         MLEVEL = ifelse(MLEVEL == "jine" & !str_detect(tn_name, "\\s"), "rod", MLEVEL),
         MLEVEL = case_when(str_detect(tn_name, "Marchantiomorpha|Hepaticae|Musci") ~ "oddeleni", # specialni pripady -> rucni prepsani
                            TRUE ~ MLEVEL)) 

# prevedeni do wide formatu + tvorba poli potrebnych pro finalni slovnik

tax_wide <- spread(tax_modif, key = MLEVEL, value = tn_name) %>% # Applying spread function
  select(tn_id, tn_tx_id, tn_authority, tn_type, oddeleni, trida, rad, celed, rod, druh, poddruh) %>% 
  
  mutate(oddeleni_ID = ifelse(!is.na(oddeleni), tn_tx_id, NA),            # ID
         trida_ID = ifelse(!is.na(trida), tn_tx_id, NA), 
         rad_ID = ifelse(!is.na(rad), tn_tx_id, NA), 
         celed_ID = ifelse(!is.na(celed), tn_tx_id, NA), 
         rod_ID = ifelse(!is.na(rod), tn_tx_id, NA), 
         druh_ID = ifelse(!is.na(druh), tn_tx_id, NA), 
         poddruh_ID = ifelse(!is.na(poddruh), tn_tx_id, NA)) %>% 
  relocate(oddeleni_ID, .before = oddeleni) %>% 
  relocate(trida_ID, .before = trida) %>% 
  relocate(rad_ID, .before = rad) %>% 
  relocate(celed_ID, .before = celed) %>% 
  relocate(rod_ID, .before = rod) %>% 
  relocate(druh_ID, .before = druh) %>% 
  relocate(poddruh_ID, .before = poddruh) %>% 
  
  mutate(oddeleni_Autor = ifelse(!is.na(oddeleni), tn_authority, NA),     # AUTOR
         trida_Autor = ifelse(!is.na(trida), tn_authority, NA), 
         rad_Autor = ifelse(!is.na(rad), tn_authority, NA), 
         celed_Autor = ifelse(!is.na(celed), tn_authority, NA), 
         rod_Autor = ifelse(!is.na(rod), tn_authority, NA), 
         druh_Autor = ifelse(!is.na(druh), tn_authority, NA), 
         poddruh_Autor = ifelse(!is.na(poddruh), tn_authority, NA)) %>% 
  relocate(oddeleni_Autor, .before = oddeleni) %>% 
  relocate(trida_Autor, .before = trida) %>% 
  relocate(rad_Autor, .before = rad) %>% 
  relocate(celed_Autor, .before = celed) %>% 
  relocate(rod_Autor, .before = rod) %>% 
  relocate(druh_Autor, .before = druh) %>% 
  relocate(poddruh_Autor, .before = poddruh) 

# doplneni NA poli 

tax_strom <- tax_wide %>%
  mutate(BU_DRUH = druh,
         BU_PODDRUH = poddruh) %>% # backup column for druh and poddruh
  filter(tn_type == 0) %>%  # work only with preffered names, filter out synonyms (1)
  
  fill(oddeleni, .direction = "down") %>%  # group and fill the taxonomy
  fill(oddeleni_ID, .direction = "down") %>%  # group and fill BioLib ID
  fill(oddeleni_Autor, .direction = "down") %>%  # group and fill BioLib Autor
  fill(trida, .direction = "down") %>%  
  fill(trida_ID, .direction = "down") %>% 
  fill(trida_Autor, .direction = "down") %>% 
  
  group_by(oddeleni, trida) %>% 
  fill(rad, .direction = "down") %>% 
  fill(rad_ID, .direction = "down") %>% 
  fill(rad_Autor, .direction = "down") %>% 
  
  group_by(oddeleni, trida, rad) %>%
  fill(celed, .direction = "down") %>% 
  fill(celed_ID, .direction = "down") %>% 
  fill(celed_Autor, .direction = "down") %>% 
  
  group_by(oddeleni, trida, rad, celed) %>%
  fill(rod, .direction = "down") %>%  # zbytecne ?
  fill(rod_ID, .direction = "down") %>%  
  fill(rod_Autor, .direction = "down") %>%  
  # group_by(oddeleni, trida, rad, celed, rod) %>%
  # fill(druh, .direction = "down") %>% 
  # group_by(oddeleni, trida, rad, celed, rod, druh) %>%
  # fill(poddruh, .direction = "down") %>% 
  ungroup() 

# check <- tax_strom %>% 
#   select(rod, druh) %>% 
#   mutate(druh1 = word(druh, 1)) %>% 
#   filter(rod != druh1)
  
  
# doplneni rodu a druhu, kde chybi + prejmenovat na _Nomen

tax_rodr <- tax_strom %>% 
  
  mutate(CHYBIDRUH = ifelse(is.na(druh), 1, 0),
         druh = ifelse(is.na(druh), paste(word(poddruh, 1), word(poddruh, 2)), druh), # take rod from the druh name (= more precise)
         druh = gsub("NA NA", NA, druh)) %>%
  
  mutate(CHYBIROD = ifelse(is.na(rod), 1, 0),
         rod = ifelse(is.na(rod), word(druh, 1), rod)) %>% # take rod from the druh name (= more precise))
  unite(sys_tree, c("oddeleni", "trida", "rad", "celed", "rod", "druh"), # "poddruh"
        sep = "/", na.rm = T, remove = FALSE) %>%   # create systematic tree
  relocate(sys_tree, .after = tn_type) %>% 
  select(-BU_DRUH,-BU_PODDRUH) %>% 
  rename(oddeleni_Nomen = oddeleni, trida_Nomen = trida, rad_Nomen = rad, celed_Nomen = celed, 
         rod_Nomen = rod, druh_Nomen = druh, poddruh_Nomen = poddruh)

length(unique(tax_rodr$rod_Nomen)) # 593
colnames(tax_rodr)

# nekde nesedi rod a rodove jmeno !!

tax_rod <- tax_rodr %>% 
  mutate(druh1 = word(druh_Nomen , 1),
         rod_ID = ifelse(rod_Nomen == druh1|is.na(druh_Nomen), rod_ID, NA)) %>% 
  mutate(rod_Nomen = ifelse(is.na(rod_ID), NA, case_when(rod_Nomen == druh1 ~ rod_Nomen,
                                                         TRUE ~ druh1))) %>% 
  mutate(rod_Nomen = case_when(rod_Nomen == druh1 ~ rod_Nomen,
                               is.na(rod_Nomen)&!is.na(druh1) ~ druh1,
                               TRUE ~ druh1))

# doplnit ceske nazvy z tabulky 'com', parovat pres 'com$tn_tx_id'

czm <- com %>% 
  filter(tvn_type == 0) # bez synonym

tax_mech <- tax_rod

tax_mech <- left_join(tax_mech, czm %>% select(tvn_name, tvn_tx_id), by = c("oddeleni_ID" = "tvn_tx_id")) %>% 
  relocate(tvn_name, .after = oddeleni_Nomen) %>% 
  rename(oddeleni_Nazev = tvn_name)

tax_mech <- left_join(tax_mech, czm %>% select(tvn_name, tvn_tx_id), by = c("trida_ID" = "tvn_tx_id")) %>% 
  relocate(tvn_name, .after = trida_Nomen) %>% 
  rename(trida_Nazev = tvn_name)

tax_mech <- left_join(tax_mech, czm %>% select(tvn_name, tvn_tx_id), by = c("rad_ID" = "tvn_tx_id")) %>% 
  relocate(tvn_name, .after = rad_Nomen) %>% 
  rename(rad_Nazev = tvn_name)

tax_mech <- left_join(tax_mech, czm %>% select(tvn_name, tvn_tx_id), by = c("celed_ID" = "tvn_tx_id")) %>% 
  relocate(tvn_name, .after = celed_Nomen) %>% 
  rename(celed_Nazev = tvn_name)

tax_mech <- left_join(tax_mech, czm %>% select(tvn_name, tvn_tx_id), by = c("rod_ID" = "tvn_tx_id")) %>% 
  relocate(tvn_name, .after = rod_Nomen) %>% 
  rename(rod_Nazev = tvn_name)

tax_mech <- left_join(tax_mech, czm %>% select(tvn_name, tvn_tx_id), by = c("druh_ID" = "tvn_tx_id")) %>% 
  relocate(tvn_name, .after = druh_Nomen) %>% 
  rename(druh_Nazev = tvn_name)

tax_mech <- left_join(tax_mech, czm %>% select(tvn_name, tvn_tx_id), by = c("poddruh_ID" = "tvn_tx_id")) %>% 
  relocate(tvn_name, .after = poddruh_Nomen) %>% 
  rename(poddruh_Nazev = tvn_name)

# doplneni ceskych nazvu rod <- druh <- poddruh

tax_cz <- tax_mech %>% 
  mutate(druh_Nazev = ifelse(is.na(druh_Nazev), paste(word(poddruh_Nazev, 1), word(poddruh_Nazev, 2)), druh_Nazev),
         rod_Nazev = ifelse(is.na(rod_Nazev), word(druh_Nazev, 1), rod_Nazev))

```



# O H R O Z E N I

Seznamy ohrozeni stazeny z https://pladias.cz/download/features (dodala pani Tkacikova).  

```{r}

# L O A D   M U S E I O N

mtax <- read_excel(paste0(path, "gen_tabdata/muzbe_taxony_MUSEION.xlsx"))   # taxony z musionu MUZBE

# L O A D   O H R O Z E N I

# # sez <- "Cerveny_seznam_2012"
# # sez <- "Cerveny_seznam_2017_(narodni_kategorie_ohrozeni)"
# # sez <- "Cerveny_seznam_2017_(kategorie_ohrozeni_IUCN)"
# sez <- "Zakonna_ochrana"
# katohr <- read_excel(paste0(path_bio, "OHROZENI/", sez, ".xlsx")) %>% 
#   rename(taxon = 1, ohr = 2, domin = 3, frekv = 4, koment = 5)
# ohr <- left_join(mtax, katohr, by = c("nomen" = "taxon")) %>% 
#   filter(!is.na(ohr))
# f2s <- paste0("M:/03 klienti/kraj moravskoslezsky/muzeum beskyd - MUZBE/02 muzBE konverze/muzbe BIO/MUZBE_ohrozeni_dle_", sez, "_n", count(ohr), ".csv")
# if(file.exists(f2s)){
#   print("You've been here before!")
#   rm(f2s)
# } else {
#   write.table(ohr, file = f2s,
#             quote = T, row.names = F, 
#             sep = ";", dec = ",", 
#             na = "",  fileEncoding="cp1250")
#   print("File  W R I T T E N  !")
#   rm(f2s)
#   }

# J E D N A   T A B U L K A 

nar <- read_excel(paste0(path_bio, "OHROZENI/Cerveny_seznam_2017_(narodni_kategorie_ohrozeni).xlsx")) %>% 
  # rename(taxon = 1, ohr = 2, domin = 3, frekv = 4, koment = 5)
  select(taxon = 1, ohr_nar = 2) %>% 
  mutate(ohr_nar = ifelse(ohr_nar == "taxon není zařazen do Červeného seznamu", NA, ohr_nar))
iuc <- read_excel(paste0(path_bio, "OHROZENI/Cerveny_seznam_2017_(kategorie_ohrozeni_IUCN).xlsx")) %>% 
  select(taxon = 1, ohr_iucn = 2) 
zak <- read_excel(paste0(path_bio, "OHROZENI/Zakonna_ochrana.xlsx")) %>% 
  select(taxon = 1, ohr_zak = 2) %>% 
  mutate(ohr_zak = case_when(ohr_zak == "ohrožený taxon" ~ "O",
                             ohr_zak == "silně ohrožený taxon" ~ "SO",
                             ohr_zak == "kriticky ohrožený taxon" ~ "KO",
                             TRUE ~ NA))

# ohr1 <- left_join(mtax[ , c("nomen")], nar, by = c("nomen" = "taxon")) # pro pani Tkacikovou
ohr1 <- left_join(mtax, nar, by = c("nomen" = "taxon")) # pro Danu (s ID)
ohr2 <- left_join(ohr1, iuc, by = c("nomen" = "taxon"))
ohr3 <- left_join(ohr2, zak, by = c("nomen" = "taxon")) 

ohr4 <- ohr3 %>% 
  filter(!if_all(c(ohr_nar, ohr_iucn, ohr_zak), ~ is.na(.)))

# ohr5 <- ohr3 %>% 
#   filter(if_all(c(ohr_nar, ohr_iucn, ohr_zak), ~ is.na(.))) # check

rm <- sample_n(ohr3, 10) # check
  
ohr <- ohr4 %>% 
  unite(ohrozeni, c("ohr_nar", "ohr_iucn", "ohr_zak"), sep = ", ", na.rm = T) 


# write.xlsx(ohr, file = "M:/03 klienti/kraj moravskoslezsky/muzeum beskyd - MUZBE/02 muzBE konverze/muzbe BIO/MUZBE_ohrozeni_zkraceno.xlsx") # pro pani Tkacikovou

f2s <- paste0("M:/03 klienti/kraj moravskoslezsky/muzeum beskyd - MUZBE/02 muzBE konverze/muzbe BIO/MUZBE_ohrozeni_FINALNI.csv") # pro Danu (s ID)

if(file.exists(f2s)){
  print("You've been here before!")
  rm(f2s)
} else {
  write.table(ohr, file = f2s,
            quote = T, row.names = F,
            sep = ";", dec = ",",
            na = "",  fileEncoding="cp1250")
  print("File  W R I T T E N  !")
  rm(f2s)
}

```

