---
title: "AXIELL piskoviste"
subtitle: "Prostredi pro zkouseni novych postupu"
author: "Kateřina Křížová"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: false
    fig_caption: true
  fontsize: 11pt
  geometry: margin=1in

---
# B A S E

```{r}
require(tidyverse)
require(readxl)
require(stringr) # ::str_split_fixed
require(stringi) # ::stri_detect_fixed - detect empty string
require(mdbr) # ::read_mdb
require(RODBC) # ::read_mdb
require(odbc) # ::read_mdb
require(xlsx) # write excel in sheets

path_snd <- "C:/Users/krizova/Documents/R/data/_piskoviste/"
```

\newpage 

# X M L

## import

PACKAGES: "XML", "xml2", "methods", "tibble"
ARTICLES: https://appsilon.com/r-xml/  ;  https://www.w3schools.com/xml/schema_howto.asp

```{r XML IMPORT}

install.packages("XML")
require(XML)

install.packages("xml2")
require(xml2)

install.packages("methods")
require(methods)

install.packages("tibble")
require(tibble)

# funkcni prikazy
xml <- xml2::read_xml("C:/Users/krizova/Documents/R/data/_piskoviste/10918171.xml", as_html = F) 
xsd <- xml2::read_xml("C:/Users/krizova/Documents/R/data/_piskoviste/priloha_c_1_CAIR_CEMUZ_e4g.xsd")

xml2::xml_validate(xml1, xsd) # TRUE - what does this mean?
structure <- xml2::xml_structure(xml) # ?
namesp <- xml2::xml_set_namespace(xml, uri = "http://www.w3.org/2001/XMLSchema-instance") # 


xml <- xml2::xmlParse(xml)

dataframe <- XML::xmlToDataFrame("C:/Users/krizova/Documents/R/data/_piskoviste/10918171.xml") # ok
dataframe <- XML::xmlToDataFrame("C:/Users/krizova/Documents/R/data/_piskoviste/grafikaupr.xml") # jiny format, nenacita spravne
dataframe <- XML::xmlToDataFrame("C:/Users/krizova/Documents/R/data/_piskoviste/PRM_BioLib_090_Fungi_Trida.xml") # ok
print(dataframe)



# lokalni piskoviste

data <- XML::xmlParse(xml)
rootnode <- XML::xmlRoot(data)
nodes <- XML::xmlSize(rootnode)
second_node <-rootnode[2]
attri <- rootnode[[3]][[4]]

cat('number of nodes: ', nodes)
print ('details of 2 record: ')
print (second_node)
print ('3rd attribute of 4th record: ', attr) 

# nefunkcni

xml_structure(xml) # doesnt work
xml_find_all(xml, ".//position") # doesnt work

dept <- XML::xml_text(xml_find_all(xml, ".//department"))
salary <- XML::xml_text(xml_find_all(xml, ".//salary"))

xmltib <- tibble(department = dept, salary = salary)


df_employees <- XML::xmlToDataFrame(nodes = XML::getNodeSet(xml, "//employee"))

#----------------------------- B R N O -------------------------------------------

xml <- XML::xmlParse("C:/Users/krizova/Documents/R/data/_piskoviste/10918171.xml") 
print(xml)

# rootnode <- XML::xmlRoot(xml)
# nodes <- XML::xmlSize(rootnode)
# second_node <- rootnode[2]
# attri <- rootnode[[4]][[3]]
# 
# dataframe <- XML::xmlToDataFrame("C:/Users/krizova/Documents/R/data/_piskoviste/10918171.xml") # nefunguje

# now
# https://urbandatapalette.com/post/2021-03-xml-dataframe-r/

install.packages("xml2")
require(xml2)
restaurant_license_xml <- as_list(read_xml("C:/Users/krizova/Documents/R/data/_piskoviste/10918171.xml"))

xml_df <- tibble::as_tibble(restaurant_license_xml) %>%
  unnest_longer(import)

lp_wider <- xml_df %>%
  dplyr::filter(import_id == "Podskup") %>%
  unnest_wider(import, names_sep = "_" )

lp_df = lp_wider %>%
  # 1st time unnest to release the 2-dimension list?
  unnest(cols = names(.)) %>%
  # 2nd time to nest the single list in each cell?
  unnest(cols = names(.)) %>%
  # convert data type
  readr::type_convert() 

myFun <- function(data) {
  temp1 <- sapply(data, is.list)
  temp2 <- do.call(
    cbind, lapply(data[temp1], function(x) 
      data.frame(do.call(rbind, x), check.names=FALSE)))
  cbind(data[!temp1], temp2)
}


xml_unlist <- myFun(xml_df)
xml_unlist2 <- tidyr::unnest_longer(xml_unlist, value)

un <- unlist(xml_df)
print(un)


# flat xml

# install.packages("flatXML")
# install.packages("devtools")
# require(devtools)
# install_github("https://github.com/jsugarelli/flatxml/")
# require(flatxml)
install.packages("xmlconvert", dependencies = TRUE)
require(xmlconvert)

fx <- fxml_importXMLFlat()
fxdf <- xml_to_df("C:/Users/krizova/Documents/R/data/_piskoviste/10918171.xml")

```

# D E M Z

```{r PACKAGES}

require(xml2)

```


```{r PISKOVISTE}

xml1 <- as_list(read_xml("C:/Users/krizova/Documents/R/data/_piskoviste/10918171.xml"))
xml2 <- as_list(read_xml("P:/w4dz/migrace/boj/26272175.xml"))
xml3 <- as_list(read_xml("P:/w4dz/migrace/boj/26280130.xml"))
xml4 <- as_list(read_xml("P:/w4dz/migrace/boj/26282696.xml"))
xml5 <- as_list(read_xml("P:/w4dz/migrace/boj/26332340.xml"))

path_xml <- "P:/w4dz/migrace/"
fold <- "boj"
# fold <- "zmt"
Lx <- c("10918171.xml", "26272175.xml", "26280130.xml", "26282696.xml", "26332340.xml")

infoex <- data.frame()

for (i in Lx) {
  a <- as_list(read_xml(paste0(path_xml, fold, "/", i)))
  b <- tibble::as_tibble(a) %>%
  unnest_longer(import)
  c <- b %>%
  dplyr::filter(import_id == "PrirCisl") %>%
  unnest_wider(import, names_sep = "_")
  s <- c[1]
  infoex <- rbind(infoex, s)
}

```


*!!! NIZE JEN OVERENE A FUNKCNI PRIKAZY !!!*    

```{r LOAD AND EDIT XML}

# L I S T   O F   F I L E S ^

Lxml_boj <- list.files("P:/w4dz/migrace/boj/", pattern = "xml") # 182
Lxml_zmt <- list.files("P:/w4dz/migrace/zmt/", pattern = "xml") # 59795

Lxml <- c(Lxml_boj, Lxml_zmt) # 59977


# L O O P   F O R   E X T R A C T I N G   S P E C.   I N F O

infoex <- data.frame() # info export dataframe

for (i in Lxml_boj) {
  a <- as_list(read_xml(paste0(path_xml, fold, "/", i))) # read xml
  b <- tibble::as_tibble(a) %>%  
  unnest_longer(import)
  c <- b %>%
  dplyr::filter(import_id == "Signatura") %>%
  unnest_wider(import, names_sep = "_")
  s <- c[1]
  infoex <- rbind(infoex, s)
}



```


# ROZMERY PTACI

MUZBE  
Pro Danu wide -> long format + poznamky.  

```{r ROZMERY PTACI}

library("tidyverse")
library("readxl")

# kolo 1

df <- read_excel(paste0(path_snd, "muzbe_rozmery_ptaci.xlsx"), sheet = 1, col_types="text")

install.packages("reshape2")
require(reshape2)

df_long <- melt(df, id.vars = c("MU_INVC", "měřil", "vážil"))

sort(unique(df_long$variable))

rozm_sna <- df_long %>% 
  group_by(MU_INVC) %>% 
  mutate(poradi = seq_along(value))

rozm_bezna <- rozm_sna %>% 
  drop_na(value) %>% 
  mutate(
    pozn = case_when(str_detect(variable, "Hmotnost|váha", negate = T)&!is.na(měřil) ~ paste("Měřil/a:", měřil),
                     str_detect(variable, "Hmotnost|váha")&!is.na(vážil) ~ paste("Vážil/a:", vážil),
                     TRUE ~ ""))

write.table(rozm_bezna, file = paste0(path_snd, "MUZBE_rozmery_ptaci_UPR.csv"),
            quote = T, row.names = F, 
            sep = ";", dec = ",", 
            na = "", fileEncoding="cp1250")

# desetinna cisla issue

dc <- rozm_bezna %>% 
  filter(str_detect(value, "\\...........*|,..........*"))

# kolo 2 - uspesne

df <- read.table(paste0(path_snd, "Pz_ZOO_Rozmery_Ptaci.txt"), header = T, sep = ";", check.names = F, fileEncoding="cp1250") %>%
  mutate(InvC = str_pad(InvC, 5, pad = "0"),
         MU_INVC = paste0("FM", InvC, "/Z")) %>% 
  relocate(MU_INVC, .after = InvC) %>% 
  select(-InvC, -Druh_CZ)

require(reshape2)

df_long <- melt(df, id.vars = c("MU_INVC", "id_meril", "id_vazil"))

sort(unique(df_long$variable))
df_long[df_long == ""] <- NA

rozm_bezna <- df_long %>% 
  drop_na(value) %>% 
  mutate(
    pozn = case_when(str_detect(variable, "vaha", negate = T)&!is.na(id_meril) ~ paste("Měřil/a:", id_meril),
                     str_detect(variable, "vaha")&!is.na(id_vazil) ~ paste("Vážil/a:", id_vazil),
                     TRUE ~ "")) %>% 
  filter(!value == "0")

write.table(rozm_bezna, file = paste0(path_snd, "MUZBE_rozmery_ptaci_UPR2.csv"),
            quote = T, row.names = F, 
            sep = ";", dec = ",", 
            na = "", fileEncoding="cp1250")

```

# BIOLIB + OHROZENI

```{r BL OHR}

# paths

path_data <- "C:/Users/krizova/Documents/R/data/"

# load

mtax <- read_excel(paste0(path_data, "_gen_tab/muzbe_taxony_MUSEION.xlsx")) %>%  # taxony z musionu
  unite(nomaut_MUS, c("nomen", "autor"), sep = " ", na.rm = T, remove = F)
aopk <- read_excel(paste0(path_data, "_gen_tab/cervene_seznamy_AOPK.xlsx"))  %>% # ohrozeni dle AOPK
  unite(nomaut_AOPK, c("ved_jm", "autor_pop"), sep = " ", na.rm = T, remove = F)

# pair author+name

rel1 <- left_join(mtax, aopk, by = c("nomaut_MUS" = "nomaut_AOPK"), keep = T)
# -> filter paired; chack names by unpaired
pair <- rel1 %>% filter(!is.na(nomaut_AOPK))
unpair <- rel1 %>% filter(is.na(nomaut_AOPK)) 

# install.packages("RecordLinkage")
require("RecordLinkage")

rel2 <- left_join(unpair, aopk, by = c("nomen" = "ved_jm"), keep = T) %>% 
  select(id, OHR = kat_ohr_iucn.y, nomen_MUS = nomen, autor_MUS = autor, 
         nomen_AOPK = ved_jm.y, autor_AOPK = autor_pop.y) %>% 
  filter(!is.na(nomen_AOPK)) %>% 
  mutate(sim = levenshteinSim(autor_MUS, autor_AOPK))

```

```{r BL AOPK OHR INTERPUNCT}

# paths

path_data <- "C:/Users/krizova/Documents/R/data/"
path_muzbe <-  "M:/03 klienti/kraj moravskoslezsky/muzeum beskyd - MUZBE/"

# load

mtax0 <- read_excel(paste0(path_data, "_gen_tab/muzbe_taxony_MUSEION.xlsx"))
mtax <- read_excel(paste0(path_data, "_gen_tab/muzbe_taxony_MUSEION.xlsx")) %>% 
  mutate(autor = ifelse(str_detect(autor, "Linneaus|Linnaeus"), gsub("Linneaus|Linnaeus", "L", autor), autor),
         Mautor_MUS = gsub("\\s|\\.|,|-|\\(|\\)|&", "", autor)) %>% 
  unite(nomaut_MUS, c("nomen", "Mautor_MUS"), sep = " ", na.rm = T, remove = F) %>% 
  select(id_MUS = id, nomen_MUS = nomen, autor_MUS = autor, Mautor_MUS, nomaut_MUS,
         cislo, nazev_1, nadtaxon, uroven, poznamka)
  
aopk <- read_excel(paste0(path_data, "_gen_tab/cervene_seznamy_AOPK.xlsx")) %>%
  mutate(autor_popL = ifelse(str_detect(autor_pop, "Linnaeus"), gsub("Linnaeus", "L", autor_pop), autor_pop),
         Mautor_AOPK = gsub("\\s|\\.|,|-|\\(|\\)|&", "", autor_popL)) %>% 
  unite(nomaut_AOPK, c("ved_jm", "Mautor_AOPK"), sep = " ", na.rm = T, remove = F) %>% 
  select(nomen_AOPK = ved_jm, autor_AOPK = autor_popL, Mautor_AOPK, nomaut_AOPK, OHR = kat_ohr_iucn)

# 1 pairing

rel1 <- left_join(mtax, aopk, by = c("nomaut_MUS" = "nomaut_AOPK"), keep = T)
# -> filter paired; chack names by unpaired
pair <- rel1 %>% filter(!is.na(nomaut_AOPK))
unpair <- rel1 %>% filter(is.na(nomaut_AOPK)) %>% select(-contains("_AOPK"), -OHR)

SAVE1 <- pair # first bunch to save

# 2 pairing

rel2 <- left_join(unpair, aopk, by = c("nomen_MUS" = "nomen_AOPK"), keep = T) %>% 
  select(id_MUS, OHR, 
         nomen_MUS, autor_MUS, Mautor_MUS, 
         nomen_AOPK, autor_AOPK, Mautor_AOPK, cislo, nazev_1, nadtaxon, uroven, poznamka) %>% 
  distinct()
pair <- rel2 %>% 
  filter(!is.na(nomen_AOPK)) %>% 
  mutate(sim = levenshteinSim(Mautor_MUS, Mautor_AOPK))
unpair <- rel2 %>% filter(is.na(nomen_AOPK)) # -> nejsou ohrozene nebo je nemame v databazi

# check of 2 pairing

chdupl <- pair %>% group_by(id_MUS) %>% filter(n() !=1) # pridano distinct do rel2

# -> filter authors with year

auty <- pair %>% filter(str_detect(autor_MUS, "\\d\\d\\d\\d")) %>% 
  mutate(year_MUS = str_extract(autor_MUS, "\\d+"),
         year_AOPK = str_extract(autor_AOPK, "\\d+"))

nesedirok <- auty %>% 
  filter(year_MUS != year_AOPK) #%>% select(autor_MUS, autor_AOPK, Mautor_MUS, Mautor_AOPK, sim) 
sedirok <- auty %>% 
  filter(year_MUS == year_AOPK) %>% 
  mutate(Mautor_MUSwy = str_remove(Mautor_MUS, "\\d+"),
         Mautor_AOPKwy = str_remove(Mautor_AOPK, "\\d+"),
         sim = levenshteinSim(Mautor_MUSwy, Mautor_AOPKwy)) %>% 
  select(id_MUS, OHR, nomen_MUS, autor_MUS, autor_AOPK, Mautor_MUSwy, Mautor_AOPKwy, sim, cislo, nazev_1, nadtaxon, uroven, poznamka)

# -> prosla jsem rucne, hranice sim pro stejna jmena je 0.4545
QUES1 <- nesedirok %>% filter(sim > 0.4) 
QUES2 <- nesedirok %>% filter(sim < 0.4) 
QUES3 <- auty %>% filter(is.na(year_AOPK)) 
QUES4 <- sedirok %>% filter(sim <= 0.2) 
SAVE2 <- sedirok %>% filter(sim > 0.2) 

# -> filter rows without year

woy <- pair %>% filter(str_detect(autor_MUS, "\\d+", negate = T)) %>% 
  # select(autor_MUS, autor_AOPK, Mautor_MUS, Mautor_AOPK) %>% 
  mutate(sim = levenshteinSim(Mautor_MUS, Mautor_AOPK))

SAVE3 <- woy %>% filter(sim > 0.16666667) 
QUES5 <- woy %>% filter(sim <= 0.16666667) 
QUES6 <- woy %>% filter(is.na(Mautor_AOPK)) 

# combine

QUES1 <- QUES1 %>% select(id_MUS, OHR, nomen_MUS, autor_MUS, autor_AOPK) %>% mutate(issue = "autor ano, rok ne")
QUES2 <- QUES2 %>% select(id_MUS, OHR, nomen_MUS, autor_MUS, autor_AOPK) %>% mutate(issue = "autor ne, rok ne")
QUES3 <- QUES3 %>% select(id_MUS, OHR, nomen_MUS, autor_MUS, autor_AOPK) %>% mutate(issue = "autor ano, rok NA")
QUES4 <- QUES4 %>% select(id_MUS, OHR, nomen_MUS, autor_MUS, autor_AOPK) %>% mutate(issue = "autor ne, rok ano")
QUES5 <- QUES5 %>% select(id_MUS, OHR, nomen_MUS, autor_MUS, autor_AOPK) %>% mutate(issue = "autor ne")
QUES6 <- QUES6 %>% select(id_MUS, OHR, nomen_MUS, autor_MUS, autor_AOPK) %>% mutate(issue = "autor AOPK NA")

questionable <- bind_rows(QUES1, QUES2, QUES3, QUES4, QUES5, QUES6)

SAVE1 <- SAVE1 %>% select(id_MUS, id_MUS, OHR, nomen_MUS, autor_MUS, cislo, nazev_1, nadtaxon, uroven, poznamka)
SAVE2 <- SAVE2 %>% select(id_MUS, id_MUS, OHR, nomen_MUS, autor_MUS, cislo, nazev_1, nadtaxon, uroven, poznamka)
SAVE3 <- SAVE3 %>% select(id_MUS, id_MUS, OHR, nomen_MUS, autor_MUS, cislo, nazev_1, nadtaxon, uroven, poznamka)

matched <- bind_rows(SAVE1, SAVE2, SAVE3)

# write.table(matched, file = paste0(path_snd, "MUStaxon_AOPK_ohrozeni.csv"),
#             quote = T, row.names = F, 
#             sep = ";", dec = ",", 
#             na = "", fileEncoding="cp1250")

muzbeohr <- read.table(paste0(path_muzbe, "02 muzBE konverze/BIO/muzbe_VSE_ohrozeni.csv"),
                       sep = ";", header = T, fileEncoding="cp1250")

merge <- full_join(matched, muzbeohr, by = c("id_MUS" = "MUS_ID")) %>% 
  select(-AOPK_ohrozeni, -MPODSB, -MNOMEN, -MINVC) %>% 
  distinct() %>% 
  group_by(id_MUS) %>%
  filter(n() == 1)

chdupl <- merge %>% group_by(id_MUS) %>% filter(n() !=1) %>% filter(duplicated(id_MUS)|n()==1)

fin <- bind_rows(merge, chdupl) # checked -> no duplicates

fin[fin == ""] <- NA

write.table(fin, file = paste0(path_data, "MUStaxon_AOPK_MUZBE_ohrozeni.csv"),
            quote = T, row.names = F,
            sep = ";", dec = ",",
            na = "", fileEncoding="cp1250")

```

# LOAD 'BF'

Impossible...

# PHP LIST

```{r}

s1 <- read.table(paste0(path_snd, "php_konf23/seznam odběratelů phpList MantisUsers.csv"),
                 header = T, sep = "\t", encoding = "utf-8")
s2 <- read.table(paste0(path_snd, "php_konf23/seznam odběratelů phpList prezentace z konference.csv"),
                 header = T, sep = "\t", encoding = "utf-8")
s3 <- read.table(paste0(path_snd, "php_konf23/seznam odběratelů phpList Prihlaseni.csv"),
                 header = T, sep = "\t", encoding = "utf-8")
s4 <- read.table(paste0(path_snd, "php_konf23/seznam odběratelů phpList UživateléMuseion.csv"),
                 header = T, sep = "\t", encoding = "utf-8")
sez0 <- bind_rows(s1, s2, s3, s4)

sez <- sez0 %>% 
  select(1,13,2,15) %>% 
  rename(jmeno = 2, email = 3, seznamy = 4) %>% 
  # group_by(jmeno, email) %>% 
  # filter(n() != 1) %>% 
  distinct() %>% 
  mutate(instituce = gsub(".*@|.cz$|.sk$|.cz>", "", email),
         instituce = ifelse(instituce == "gmail.com", "neidentifikovano", instituce),
         instituce = ifelse(instituce == "seznam", "neidentifikovano", instituce)) %>% 
  relocate(seznamy, .after = instituce) %>% 
  arrange(instituce)
  
write.xlsx(sez, file = paste0(path_snd, "php_konf23/phpList_seznam.xlsx"), row.names = F)

```

