---
title: "Kontrola CES × MUSEION"
subtitle: "zjištěný stav k"
date: "`r Sys.Date()`"
author: "Katerina Krizova"
output:
  pdf_document
    toc: true
    toc_depth: 2
    number_sections: F
    fig_caption: true
  fontsize: 11pt
  geometry: margin=1in

---

\newpage 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message=FALSE, fig.dim = c(8, 4))

# PACKAGES

# install.packages("tidyverse", dependencies = T)
# install.packages("readxl")
# install.packages("stringr")
# install.packages("stringi")
# install.packages("mdbr")
# install.packages("RODBC")
# install.packages("odbc")
# install.packages("xlsx")
require(tidyverse)
require(readxl)
require(xlsx) # write excel in sheets
require(stringr) # ::str_split_fixed
require(stringi) # ::stri_detect_fixed - detect empty string
require(mdbr) # ::read_mdb
require(RODBC) # ::read_mdb
require(odbc) # ::read_mdb

```

\newpage 

# ------------------------------------ prep 

# PATHS AND PROJ INFO

```{r}

proj <- "MUZNJ"

path_ces <- "C:/Users/krizova/Documents/R/CES/"
path_proj <- "M:/03 klienti/kraj moravskoslezsky/muzeum novojicinska - MUZNJ/06 muzNJ konsolidace-CES/"

```

# @ LOAD CES TXT LOOP

1.sloupec = Změna {N = nove, platne; V = vyrazeni; R = ruseni}
2.sloupec = Duvod (pro N vypusteno)
            V {N = neupotrebitelnost; P = prebytecnost; R = rozepsani; O = omyl}
            R {C = chyba; Z = zmena cislovani}
3. sloupec = typ cisla {P = prirustkove; I = inventarni}
            
```{r LOAD CES TXT LOOP , warning = F}

# FUNKCNI SMYCKA PRO NACITANI CES EXPORTNICH TXT 

Ltxt <- list.files(paste0(path_proj, "vypCES"), pattern = "*.txt")  # Identify file names
df_filled <- data.frame()
colnam <- c("zmena","duvod","typ_cisla","cislo",
                "s5","s6", "s7", "s8",
                "s9","s10","s11","s12")
    
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

a <- read.table(paste0(path_proj, "vypCES/", Ltxt[1]),
                  skip = 4, header = F, sep = ";", fill = T, 
                  check.names = F, fileEncoding="cp1250")

for(i in Ltxt) {
  a <- read.table(paste0(path_proj, "vypCES/", i),
                  skip = 4, header = F, sep = ";", fill = T, 
                  check.names = F, fileEncoding="cp1250")
  names(a) <- colnam
  rows_to_change <- a$zmena == "N"
  a[rows_to_change,3:12] <- a[rows_to_change,2:12] # shift columns with N
  a[rows_to_change,2] <- NA
  a$zdroj <- paste(i) # add source txt file name
  a <- a %>% filter(str_detect(zmena, ("^N$|^V$|^R$")))  # filter only relevant rows !!!
  # print(unique(a$zdroj))
  print(count(a))
  df_filled <- rbind(df_filled,a)
  print(i)
}

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# SAVE ALL TXT

f2s <- paste0(path_ces, proj, "/", proj, "_allTXT.csv")

if(file.exists(f2s)){
  print("TXT already saved")
  rm(f2s)
} else {
  write.table(df_filled, file = f2s, 
            quote = T, row.names = F, 
            sep = ";", dec = ",", 
            na = "", fileEncoding="cp1250")
  rm(f2s)
}

# CHECK AND CLEAR ENVIRONMENT

rm(a)
rm(i)
rm(colnam)
rm(rows_to_change)

```

```{r READ ALREADY SAVED TXT}

df_filled <- read.csv("C:/Users/krizova/Documents/R/CES/MUZNJ/MUZNJ_allTXT.csv", header = T, sep = ";", fileEncoding="cp1250")

```

# ------------------------------------ parc

# CES EDITS

```{r CES PROCESSING}

CORE_ces <- df_filled %>% discard(~all(is.na(.) | . == "")) # drop empy columns
 
CORE_ces[CORE_ces == ""] <- NA

sort(unique(CORE_ces$zmena))
sort(unique(CORE_ces$duvod))
sort(unique(CORE_ces$typ_cisla))

# DUPLICITY

check <- CORE_ces %>% 
  group_by(typ_cisla, cislo, zmena) %>% 
  mutate(is_dupl = case_when(n() != 1&zmena == "R" ~ "dupl", TRUE ~ NA)) %>% 
  ungroup()

SAVE_dupl <- check %>% filter(is_dupl == "dupl")
# UPDT_ces <- check %>% filter(is.na(is_dupl))              # EXECUTE: nrow(SAVE_dupl)+nrow(UPDT_ces)==nrow(CORE_ces)

UPDT_ces <- CORE_ces

# PROCESS. EXCEL

# temp <- as.data.frame(sort(unique(UPDT_ces$zdroj)))

```

# MUS EDITS

```{r}

CORE_mus_pk <- read_excel(paste0(path_proj, "vypMUS/muznj_MUSEION_PK.xlsx"), 
                  sheet = 1, col_types="text") %>% 
  mutate(id = floor(as.numeric(id)), # upravy formatu cisel a vytvoreni MMUS_par pro parovani
         id =  as.character(id),
         poradovecislo = trunc(as.numeric(poradovecislo)),
         poradovecislo = as.character(poradovecislo))


CORE_mus_ka <- read_excel(paste0(path_proj, "vypMUS/muznj_MUSEION_SP.xlsx"), 
                  sheet = 1, col_types="text") %>% 
    mutate(sp_id = floor(as.numeric(sp_id)), # upravy formatu cisel a vytvoreni MMUS_par pro parovani
         sp_id = as.character(sp_id),
         sp_porcislo = trunc(as.numeric(sp_porcislo)),
         sp_porcislo = as.character(sp_porcislo))

```

rm(df_filled)
rm(check)


# ------------------------------------ proc

# PK

```{r}

# ZRUSENE

pk_rus  <- UPDT_ces %>% 
  filter(typ_cisla == "P") %>% 
  # filter(zdroj == podsb_ces) %>% 
  filter(zmena == "R") 

# CES PK EDITS

pk <- UPDT_ces %>% filter(typ_cisla == "P") %>% 
    mutate(Mrada = ifelse(str_detect(cislo, "\\s"), gsub("\\s.*$", "", cislo), NA),
           Mcislo =ifelse(str_detect(cislo, "\\s"), gsub("^.*\\s", "", cislo), cislo)) %>% 
    separate(Mcislo, into=c("Mporc", "Msub1", "Msub2", "Msub3") , sep="\\/", extra = "merge", remove = F) %>% 
    unite(MCES_par, c("Mrada", "Mporc", "Msub1", "Msub2", "Msub3"), sep = "/", na.rm = T, remove = FALSE) %>% 
    select(zdroj, typ_cisla, zmena, duvod, CES_cislo = cislo, MCES_par) %>%
    filter(zmena!="R") 

# MUS PK EDITS

mus <- CORE_mus_pk %>%
    mutate(Mrada = str_extract(cislo, "^[:alpha:]+"),
           Mcislo = str_remove(cislo, "^[:alpha:]+")) %>% 
    separate(Mcislo, into=c("Mporc", "Msub1", "Msub2", "Msub3") , sep="\\/", extra = "merge", remove = F) %>%
    mutate(Mporc = gsub("^0+", "", Mporc), # --------------------------------------------------------------------- odstr. vedouci nuly
           Msub1 = ifelse(str_detect(Msub1, "^0+$"), Msub1, gsub("^0+", "", Msub1)),
           Msub2 = gsub("^0+", "", Msub2),
           Msub3 = gsub("^0+", "", Msub3)) %>% 
    unite(MMUS_par, c("Mrada", "Mporc", "Msub1", "Msub2", "Msub3"), sep = "/", na.rm = T, remove = FALSE)

# RELATE

rel <- left_join(pk, mus, by = c("MCES_par" = "MMUS_par"), keep = T) %>% 
  select(zdroj, typ_cisla, zmena, duvod, CES_cislo, MCES_par,
         MMUS_par, MUS_cislo = cislo, id, cisloCES, nazev) # EXECUTE: nrow(rel)==nrow(pk)

APND_pk_spa <- rel %>% filter(!is.na(MMUS_par))

# ANALYZE

no <- sum(is.na(rel$MMUS_par))
yo <- sum(!is.na(rel$MMUS_par))
ratio <- round(sum(yo)/nrow(pk)*100, 2)
ap_stats <- cbind(nrow(rel), yo, no, ratio) 
APND_stats <- data.frame()
APND_stats <- rbind(APND_stats, ap_stats)

# NESPA 1

nespa <- rel %>% filter(is.na(MMUS_par)) %>% 
  select(zdroj, typ_cisla, zmena, duvod, CES_cislo, MCES_par) %>% 
  separate(MCES_par, into=c("Mrada", "Mporc", "Msub1", "Msub2", "Msub3") , sep="\\/", extra = "merge", remove = F) 

rel <- left_join(nespa, mus, by = c("Mrada", "Mporc", "Msub1", "Msub2"), keep = T) %>% 
  select(zdroj, typ_cisla, zmena, duvod,CES_cislo, MCES_par,
         MMUS_par, MUS_cislo = cislo, id, cisloCES, nazev)

spa <- rel %>% filter(!is.na(MMUS_par))
APND_pk_spa <- bind_rows(APND_pk_spa, spa)

no <- sum(is.na(rel$MMUS_par))
yo <- sum(!is.na(rel$MMUS_par))
ratio <- round(sum(yo)/nrow(pk)*100, 2)
ap_stats <- cbind(nrow(rel), yo, no, ratio) 
APND_stats <- rbind(APND_stats, ap_stats)

nespa <- rel %>% filter(is.na(MMUS_par)) %>% 
  select(zdroj, typ_cisla, zmena, duvod, CES_cislo, MCES_par) %>% 
  separate(MCES_par, into=c("Mrada", "Mporc", "Msub1", "Msub2", "Msub3") , sep="\\/", extra = "merge", remove = F) 

```

# ------------------------------------ prep 

# ------------------------------------ prep 

# ------------------------------------ prep 

# ------------------------------------ prep 

# ------------------------------------ prep 
