---
title: "RMD for notes"
subtitle: ""
author: "Katerina Krizova"
date:  "`r Sys.Date()`"
output:
  pdf_document
    toc: true
    toc_depth: 2
    number_sections: false
    fig_caption: true
  fontsize: 11pt
  geometry: margin=1in

---

\newpage 

# R general tips

- pojmenovavej df s prefixem, at se hezky radi v environmentu

- pri duplikovanem invc podlomit '/dupl1' a '/dupl2' oba zaznamy

# MIG tips

## naming conventions

- Mname = name of working column 
- MNAME = final name of column

## process

- *wip_tab* = work-in-progress tab (try everything out here)
- *mod_tab* = result of modifications, source for building od a mus_tab
- *mus_tab* = final CSV for import

# OBRAZKY

! nejprve zkontroluj vsechny vyskytujici se pripony ! (meli jsme i *.png)

- *sez* = list of jpg
- *jpg* = list of MINVC for pairing

- *MFN* = M file name (FM 53753.jpg)
- *MFC* = M file number (53753)

\newpage
 
# OMCV CES - script rearrangement

## CES INVC

# MUZTE MIGRACE

1) v jednom pripade podskupina 'Tracheopyhta' -> opraveno na 'Tracheophyta'
2) ADRESAR$create_uid: ztotozneno: 'Buša E.' -> 'Burša E.' ; 'svendova' a 'Svendova'
3) ADRESAR$sberatel: ztotozneno: "Buša E." -> "Burša E." ; "Kousalová Š:" -> "Kousalová Š." ; Pavlíkovi P. A J. -> Pavlíkovi P. a J. ; D. Podstawková -> Podstawková D.
4) ADRESAR$sberatel: ztotozneno: "Buša E." "BUrša E."-> "Burša E." ; Pavlíkovi P. A J. -> Pavlíkovi P. a J.
5) ADRESAR$urcil: koupě invc: 1142
