---
title: "JMCB PK"
author: "Kateřina Křížová"
date: "`r Sys.Date()`"
author: "Katerina Krizova"
output:
  pdf_document
    toc: true
    toc_depth: 2
    number_sections: F
    fig_caption: true
  fontsize: 11pt
  geometry: margin=1in
---


\newpage 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message=FALSE, fig.dim = c(8, 4))

# PACKAGES

# install.packages("tidyverse", dependencies = T)
# install.packages("readxl")
# install.packages("stringr")
# install.packages("stringi")
# install.packages("mdbr")
# install.packages("RODBC")
# install.packages("odbc")
# install.packages("xlsx")
# install.packages("data.table")
# install.packages("Matrix")
require(tidyverse)
require(readxl)
require(xlsx) # write excel in sheets
require(stringr) # ::str_split_fixed
require(stringi) # ::stri_detect_fixed - detect empty string
require(mdbr) # ::read_mdb
require(RODBC) # ::read_mdb
require(odbc) # ::read_mdb
library(Matrix) 
library(data.table) # ::rbindlist 

```

\newpage 

# PATHS AND PROJ INFO

```{r}

proj <- "JMCB"

path_proj <- "M:/03 klienti/kraj jihocesky/jihoceske muzeum v ceskych budejovicich - JMCB/03 migrace/jmcb migrace 2023/"
path_kk <- paste0(path_proj, "KK_workspace/")

# path_data <- "M:/03 klienti/kraj jihocesky/jihoceske muzeum v ceskych budejovicich - JMCB/2023_PK/zdrojdat/orig/"

```

# READ

7 excelu, kazdy obsahuje listy s roky
18xx 20xx 68-79 1900-1921 1953-1979 1980-99 1980-1999

```{r}

# single-sheet

# df68 <- readxl::read_excel(paste0(path_proj, "68-79.xlsx"), sheet = 1, col_types = "text") # prekryv s df53
# df80 <- readxl::read_excel(paste0(path_proj, "80-99.xlsx"), sheet = 1, col_types = "text")

# multi-sheets

read_excel_allsheets <- function(filename, tibble = FALSE) {
    # I prefer straight data.frames
    # but if you like tidyverse tibbles (the default with read_excel)
    # then just pass tibble = TRUE
    sheets <- readxl::excel_sheets(filename)
    x <- lapply(sheets, function(X) readxl::read_excel(filename, sheet = X, col_types = "text", col_names = F,))
    if(!tibble) x <- lapply(x, as.data.frame)
    names(x) <- sheets
    x
}

# eda -> predelano, df az po nacteni

# a <- c("df18", colnames(df18))
# b <- c("df19", colnames(df19))
# c <- c("df20", colnames(df20))
# d <- c("df53", colnames(df53))
# e <- c("df80", colnames(df80))
# 
# eda <- rbind(a, b, c, d, e, deparse.level = 0)

```

df18 = 18xx
df19 = 1900-1921
df53 = 1953-1979
df68 = 68-79
df80 = 80-99
df20 = 20xx

# PROCESS

## df18 

pro excel 18xx

```{r}

# read

mysheets <- read_excel_allsheets(paste0(path_kk, "18xx.xlsx")) # specifikuj excel file
df18 <- as.data.frame(rbindlist(mysheets, fill = T))
names(df18) <- df18[1,]
df18 <- df18 %>% filter(is.na(rok)|rok!="rok") # vymaze vsechny radky, ktere jsou hlavicky puvodnich listu

rm(mysheets)

# obecne

aa <- df18 %>% 
  mutate(sbirka1 = "JMCB"
         podsb2 = ,
         cisrada3 = ,
         typ30 = "P",
         rok12 = rok,
         pocetks13 = poznamkaCZ)

# prirc - DOPRACOVAT

aa$porc <- as.numeric(aa$porc)

bb <- aa %>% 
  group_by(rok) %>% 
  fill(porc, .direction = "down") %>% 
  group_by(rok, porc) %>%
  mutate(Msub = case_when(n()!=1 ~ seq_along(porc), TRUE ~ NA)) %>%
  relocate(Msub, .after = porc) %>% 
  ungroup() %>% 
  mutate(prirc4 = ifelse(!is.na(Msub), paste0(rok, "/", str_pad(porc, 3, pad = "0"), "-", Msub), paste0(rok, "/", str_pad(porc, 3, pad = "0"))),
         popis11 = paste(ifelse(!is.na(popis), paste("popis: ", popis), ""),
                         ifelse(!is.na(popisCZ), paste("popisCZ: ", popisCZ), ""), sep = "\n"))

# datum nabyti a vyrazeni

cc <- bb %>% 
  mutate(datnab22 = case_when(
                            str_detect(datum, "\\d+\\/\\d+\\s....$") ~ gsub("\\/|\\s", ".", datum), # ok
                            str_detect(datum, "^\\d+\\/\\s*\\d+$") ~ paste0(str_extract(datum, "^\\d+"), ".", (str_extract(datum, "\\d+$")), ".", rok),     
                            str_detect(datum, "\\d+\\.\\s*\\d+\\.\\s*$") ~ gsub("\\s", "", paste(datum, rok)),
                            TRUE ~ datum),
         zpnab23 = case_when(str_detect(puvodCZ, "(?=.*dar)(?=.*směna)") ~ "DS",
                             str_detect(puvodCZ, "darováno|dar") & !str_detect(puvodCZ, "směna") ~ "D",
                             str_detect(puvodCZ, "směna") ~ "S",
                             str_detect(puvodCZ, "koupě|koupeno|zakoupeno") ~ "K",
                             str_detect(puvodCZ, "nalezeno") ~ "N",
                             str_detect(puvodCZ, "nadání") ~ "Na",
                             TRUE ~ NA)) %>% 
  relocate(datnab22, .after = datum) %>% 
  mutate(datvyr64 = gsub("^Odpis\\s|,\\sčj..*$", "", vyrazeni),
         dokvyr67 = gsub("^.*,\\s", "", vyrazeni),
         poznvyr73 = vyrazeni)

# puvod - DOPRACOVAT

dd <- cc %>% 
  mutate(puvmaj28 = ifelse(!is.na(puvod), puvod, ""),
         predchmaj74 = ifelse(!is.na(puvodCZ), puvodCZ, ""))

# poznamky

ee <- dd %>%
  mutate(pozn20 = ifelse(!is.na(poznamka), poznamka, ""),
         nabpozn29 = paste(ifelse(!is.na(cenaKR), paste("cenaKR:", cenaKR), ""),
                           ifelse(!is.na(cenaHA), paste("cenaHA:", cenaHA), ""),
                                  sep = "\n"),
         text1_88 = ifelse(!is.na(umisteni), umisteni, ""),
         text2_89 = ifelse(!is.na(umisteniCZ), umisteniCZ, ""))

```

## df19 

pro excel 1900-1921

```{r}
# read

mysheets <- read_excel_allsheets(paste0(path_kk, "1900-1921.xlsx"))
df19 <- as.data.frame(rbindlist(mysheets, fill = T))
names(df19) <- df19[2666,]
df19 <- df19 %>% filter(is.na(poradi)|poradi!="poradi") # vymaze vsechny radky, ktere jsou hlavicky puvodnich listu

# obecne

aa <- df19 %>% 
  mutate(sbirka1 = "JMCB",
         podsb2 = "?",
         cisrada3 = "?",
         typ30 = "P",
         ozn10 = predmet,
         rok12 = rok,
         pocetks13 = pocetks,
         text3_90 = jinecislo)

# prirc - DOPRACOVAT

aa$poradi <- as.numeric(aa$poradi)

bb <- aa %>% 
  group_by(rok) %>% 
  fill(poradi, .direction = "down") %>% 
  group_by(rok, poradi) %>%
  # mutate(Msub = case_when(n()!=1 ~ letters[seq_along(porc)], TRUE ~ NA)) %>%  # vybereme podle typu podlomeni
   # mutate(Msub = case_when(n()!=1 ~ LETTERS[seq_along(porc)], TRUE ~ NA)) %>%
   mutate(Msub = case_when(n()!=1 ~ seq_along(poradi), TRUE ~ NA),
          porc104 = poradi) %>%
  relocate(Msub, .after = poradi) %>% 
  ungroup() %>% 
  mutate(prirc4 = ifelse(!is.na(Msub), paste0(rok, "/", str_pad(poradi, 3, pad = "0"), "-", Msub), paste0(rok, "/", str_pad(poradi, 3, pad = "0"))),
         subc105 = Msub, 
         popis11 = paste(ifelse(!is.na(popis), paste("popis: ", popis), ""),
                         ifelse(!is.na(popisCZ), paste("popisCZ: ", popisCZ), ""), sep = "\n"))

# datum nabyti a vyrazeni 

cc <- bb %>% 
  mutate(datnab22 = case_when(
                            str_detect(datumNabyti, "\\d+\\/\\d+\\s....$") ~ gsub("\\/|\\s", ".", datumNabyti), # ok
                            str_detect(datumNabyti, "^\\d+\\/\\s*\\d+$") ~ paste0(str_extract(datumNabyti, "^\\d+"), ".", 
                                                                              (str_extract(datumNabyti, "\\d+$")), ".", rok),                
                            str_detect(datumNabyti, "\\/II") ~ paste0(gsub("\\/II", ".2.", datumNabyti),rok),
                            str_detect(datumNabyti, "\\d+\\.\\d+\\.$") ~ paste0(datumNabyti, rok),
                            TRUE ~ datumNabyti)) %>% 
  relocate(datnab22, .after = datumNabyti) %>% 
  mutate(vyrdat64 = gsub("^Odpis\\s+|,*\\sč.\\s*j..*$|čj.*$|,*\\s*č.*k..*", "", vyrazeni),
         vyrdok67 = str_extract(vyrazeni, "č.*$"),
         poznvyr73 = vyrazeni)
  
# az bude potvrzeno, pridat k dd.mm. i rok (z pole 'rok')

# puvod - DOPRACOVAT

dd <- cc %>% 
  mutate(puvmaj28 = ifelse(!is.na(puvod), puvod, ""),
         predchmaj74 = ifelse(!is.na(puvodCZ), puvodCZ, ""),
         zpnab23 = case_when(zpNabyti == "dar" ~ "D",
                             zpNabyti == "koupě" ~ "K",
                             zpNabyti == "předáno z městského archivu" ~ "MA",
                             zpNabyti %in% c("výměna za několik vltavínů", "výměnou za několik vltavínů") ~ "VLT"))

# poznamky

ee <- dd %>%
  mutate(pozn20 = paste(ifelse(!is.na(poznamka), paste("poznamka:", poznamka), ""),
                           ifelse(!is.na(poznamkaCZ), paste("poznamkaCZ:", poznamkaCZ), ""),
                                  sep = "\n"),
         nabpozn29 = paste(ifelse(!is.na(cenaKR), paste("cenaKR:", cenaKR), ""),
                           ifelse(!is.na(cenaHA), paste("cenaHA:", cenaHA), ""), 
                           ifelse(!is.na(zpNabyti), paste("zpNabyti:", zpNabyti), ""), 
                           sep = "\n"),
         text1_88 = ifelse(!is.na(umisteni), umisteni, ""),
         text2_89 = ifelse(!is.na(umisteniCZ), umisteniCZ, ""))

```

## df53

pro excel 1953-1979   A L E !!
odfiltrovat 68-79, ktere jsou sumarizovany v dalsim dataframu

```{r}
mysheets <- read_excel_allsheets(paste0(path_kk, "1953-1979.xlsx"))
df53 <- as.data.frame(rbindlist(mysheets, fill = T))
names(df53) <- df53[1,]
names(df53)[16] = "xpozn"
df53 <- df53 %>% filter(is.na(rokPK)|rokPK!="rokPK") # n = 27579 

# filtr roku

df53$rokPK <- as.numeric(df53$rokPK)

df53 <- df53 %>% filter(rokPK %in% 1953:1967)
        
# obecne

df53$prirc <- as.numeric(df53$prirc)

aa <- df53 %>% 
  mutate(podsb2 = podsbirka,
         ozn10 = predmet,
         popis11 = popis,
         rok12 = rokPK,
         pocetks13 = pocetKs,
         text3_90 = jinecislo)

# prirc - DOPRACOVAT

bb <- aa %>% 
  group_by(rokPK) %>% 
  fill(prirc, .direction = "down") %>% 
  group_by(rokPK, prirc) %>%
  mutate(Msub = case_when(n()!=1 ~ seq_along(prirc), TRUE ~ NA),
          porc104 = prirc) %>%
  relocate(Msub, .after = prirc) %>% 
  ungroup() %>% 
  mutate(prirc4 = ifelse(!is.na(prirc), paste0(rokPK, "/", str_pad(prirc, 4, pad = "0")), paste0("format!")),
         Minvc_sin = ifelse(str_detect(invc, "^\\d+$"), invc, ""),
         MinvcOD = ifelse(str_detect(invc, "^\\d+-\\d+$"), gsub("-.*$", "", invc), ""),
         MinvcDO = ifelse(str_detect(invc, "^\\d+-\\d+$"), gsub(".*-", "", invc), ""),
         Minvc_sez = ifelse(str_detect(invc, "\\d,\\s\\d"), gsub(",", ";", invc), "")) %>% 
  relocate(Minvc_sin, .after = invc) %>% 
  relocate(MinvcDO, .after = invc) %>% 
  relocate(MinvcOD, .after = invc) %>% 
  relocate(Minvc_sez, .after = invc)
         
  #        MinvcOD = ifelse(str_detect(invc, "\\d-\\d)"), gsub("-.*$", "", invc), ""),
  #        MinvcDO = ifelse(str_detect(invc, "\\d-\\d)"), gsub(".*-", "", invc), "")) %>% 
  # relocate(MinvcDO, .after = invc) %>% 
  # relocate(MinvcOD, .after = invc)

maxl <- max(nchar(na.omit(df19$poradi)))
maxl

# datum nabyti a vyrazeni - DOPRACOVAT

cc <- bb %>% 
  mutate(Mdat_ser = as.numeric(ifelse(str_detect(datumNabyti, "^.....$"), datumNabyti, NA)),
         Mdat_trans = format(as.Date(Mdat_ser, origin = "1899-12-30"), "%d.%m.%Y"),
         datnab22 = ifelse(str_detect(datumNabyti, "\\d\\.\\d+\\.\\d+\\."), str_remove(datumNabyti, "\\.$"), Mdat_trans)) %>% 
  relocate(datnab22, .after = datumNabyti) %>% 
  mutate(vyrdat64 = str_extract(vyrazeni, "\\d+\\.\\s*\\d+\\.\\s*\\d{4}"),
         vyrdok67 = str_extract(vyrazeni, "MK\\s+\\d+\\/\\d+\\sOM|č.\\s*j.\\s+\\d+\\/\\d+\\sOM|č.\\s*j.\\s+\\d+\\/\\d+.*G|D\\s\\d+\\/\\d+|Kult\\.*\\s\\d+\\/\\d+"),
         vyrdok67 = doklad) %>%  # ktera volba ? -> doklad nevime k cemu se vztahuje, muze to byt i doklad o nabyti atd...
  relocate(vyrazeni, .before = datvyr64)
  
# az bude potvrzeno, pridat k dd.mm. i rok (z pole 'rok')

# puvod - DOPRACOVAT

dd <- cc %>% 
  mutate(puvmaj28 = ifelse(!is.na(puvod), puvod, ""),
         zpnab23 = case_when(str_detect(zpNabyti,"Dar|dar") ~ "D",
                             str_detect(zpNabyti, "onf") ~ "Konf",
                             str_detect(zpNabyti, "Koup|koup") ~ "K",
                             str_detect(zpNabyti, "nález") ~ "N",
                             str_detect(zpNabyti, "ozůstalost") ~ "Poz",
                             str_detect(zpNabyti, "Sběr|sběr") ~ "Sb",
                             TRUE ~ "")) %>% 
  relocate(zpNabyti, .before = zpnab23)

# poznamky

ee <- dd %>%
  mutate(pozn20 = paste(ifelse(!is.na(poznamka), paste("poznamka:", poznamka), ""),
                           ifelse(!is.na(poznamkaCZ), paste("poznamkaCZ:", poznamkaCZ), ""),
                                  sep = "\n"),
         nabpozn29 = paste(ifelse(!is.na(zpNabyti), paste("zpNabyti:", zpNabyti), ""),
                           ifelse(!is.na(cenaKR), paste("cenaKR:", cenaKR), ""),
                           ifelse(!is.na(cenaHA), paste("cenaHA:", cenaHA), ""),
                                  sep = "\n"),
         text1_88 = ifelse(!is.na(umisteni), umisteni, ""),
         text2_89 = ifelse(!is.na(umisteniCZ), umisteniCZ, ""))
```


## df68 

pro excel 68-79

```{r}

df68 <- readxl::read_excel(paste0(path_proj, "68-79.xlsx"), sheet = 1, col_types = "text") 

# obecne

df68$prirc <- as.numeric(df68$prirc)

colnames(df68)

aa <- df53 %>% 
  mutate(podsb2 = podsbirka,
         ozn10 = predmet,
         popis11 = popis,
         rok12 = rokPK,
         pocetks13 = pocetKs,
         text3_90 = jinecislo,
         porc104 = prirc)

# prirc - DOPRACOVAT

bb <- aa %>% 
  mutate(prirc4 = ifelse(!is.na(prirc), paste0(rokPK, "/", str_pad(prirc, 4, pad = "0")), paste0("format!")),
         Minvc_sin = ifelse(str_detect(invc, "^\\d+$"), invc, ""),
         MinvcOD = ifelse(str_detect(invc, "^\\d+-\\d+$"), gsub("-.*$", "", invc), ""),
         MinvcDO = ifelse(str_detect(invc, "^\\d+-\\d+$"), gsub(".*-", "", invc), ""),
         Minvc_sez = ifelse(str_detect(invc, "\\d,\\s\\d"), gsub(",", ";", invc), "")) %>% 
  relocate(Minvc_sin, .after = invc) %>% 
  relocate(MinvcDO, .after = invc) %>% 
  relocate(MinvcOD, .after = invc) %>% 
  relocate(Minvc_sez, .after = invc)
         
  #        MinvcOD = ifelse(str_detect(invc, "\\d-\\d)"), gsub("-.*$", "", invc), ""),
  #        MinvcDO = ifelse(str_detect(invc, "\\d-\\d)"), gsub(".*-", "", invc), "")) %>% 
  # relocate(MinvcDO, .after = invc) %>% 
  # relocate(MinvcOD, .after = invc)

# datum nabyti a vyrazeni - DOPRACOVAT

cc <- bb %>% 
  mutate(Mdat_ser = as.numeric(ifelse(str_detect(datumNabyti, "^.....$"), datumNabyti, NA)),
         Mdat_trans = format(as.Date(Mdat_ser, origin = "1899-12-30"), "%d.%m.%Y"),
         datnab22 = ifelse(str_detect(datumNabyti, "\\d\\.\\d+\\.\\d+\\."), str_remove(datumNabyti, "\\.$"), Mdat_trans)) %>% 
  relocate(datnab22, .after = datumNabyti) %>% 
  mutate(datvyr64 = str_extract(vyrazeni, "\\d+\\.\\s*\\d+\\.\\s*\\d{4}"),
         dokvyr67 = str_extract(vyrazeni, "MK\\s+\\d+\\/\\d+\\sOM|č.\\s*j.\\s+\\d+\\/\\d+\\sOM|č.\\s*j.\\s+\\d+\\/\\d+.*G|D\\s\\d+\\/\\d+|Kult\\.*\\s\\d+\\/\\d+"),
         dokvyr67 = doklad) %>%  # ktera volba ? 
  relocate(vyrazeni, .before = datvyr64)
  
# az bude potvrzeno, pridat k dd.mm. i rok (z pole 'rok')

# puvod - DOPRACOVAT

dd <- cc %>% 
  mutate(puvmaj28 = ifelse(!is.na(puvod), puvod, ""),
         zpnab23 = case_when(str_detect(zpNabyti,"Dar|dar") ~ "D",
                             str_detect(zpNabyti, "onf") ~ "Konf",
                             str_detect(zpNabyti, "Koup|koup") ~ "K",
                             str_detect(zpNabyti, "nález") ~ "N",
                             str_detect(zpNabyti, "ozůstalost") ~ "Poz",
                             str_detect(zpNabyti, "Sběr|sběr") ~ "Sb",
                             TRUE ~ "")) %>% 
  relocate(zpNabyti, .before = zpnab23)

# poznamky

ee <- dd %>%
  mutate(pozn20 = paste(ifelse(!is.na(poznamka), paste("poznamka:", poznamka), ""),
                        ifelse(!is.na(poznamkaCZ), paste("poznamkaCZ:", poznamkaCZ), ""),
                                  sep = "\n"),
         nabpozn29 = paste(ifelse(!is.na(zpNabyti), paste("zpNabyti:", zpNabyti), ""),
                           ifelse(!is.na(cenaKR), paste("cenaKR:", cenaKR), ""),
                           ifelse(!is.na(cenaHA), paste("cenaHA:", cenaHA), ""),
                                  sep = "\n"),
         text1_88 = ifelse(!is.na(umisteni), umisteni, ""),
         text2_89 = ifelse(!is.na(umisteniCZ), umisteniCZ, ""))
```


## df80 - ip ---------------------------------

pro excel 1980-1999

```{r}

df80 <- readxl::read_excel(paste0(path_proj, "68-79.xlsx"), sheet = 1, col_types = "text") 

# obecne

df80$prirc <- as.numeric(df68$prirc)

colnames(df80)

aa <- df80 %>% 
  mutate(podsb2 = podsbirka,
         ozn10 = predmet,
         popis11 = popis,
         rok12 = rokPK,
         pocetks13 = pocetKs,
         text3_90 = jinecislo,
         porc104 = prirc)

# prirc - DOPRACOVAT

bb <- aa %>% 
  mutate(prirc4 = ifelse(!is.na(prirc), paste0(rokPK, "/", str_pad(prirc, 4, pad = "0")), paste0("format!")),
         Minvc_sin = ifelse(str_detect(invc, "^\\d+$"), invc, ""),
         MinvcOD = ifelse(str_detect(invc, "^\\d+-\\d+$"), gsub("-.*$", "", invc), ""),
         MinvcDO = ifelse(str_detect(invc, "^\\d+-\\d+$"), gsub(".*-", "", invc), ""),
         Minvc_sez = ifelse(str_detect(invc, "\\d,\\s\\d"), gsub(",", ";", invc), "")) %>% 
  relocate(Minvc_sin, .after = invc) %>% 
  relocate(MinvcDO, .after = invc) %>% 
  relocate(MinvcOD, .after = invc) %>% 
  relocate(Minvc_sez, .after = invc)
         
  #        MinvcOD = ifelse(str_detect(invc, "\\d-\\d)"), gsub("-.*$", "", invc), ""),
  #        MinvcDO = ifelse(str_detect(invc, "\\d-\\d)"), gsub(".*-", "", invc), "")) %>% 
  # relocate(MinvcDO, .after = invc) %>% 
  # relocate(MinvcOD, .after = invc)

# datum nabyti a vyrazeni - DOPRACOVAT

cc <- bb %>% 
  mutate(Mdat_ser = as.numeric(ifelse(str_detect(datumNabyti, "^.....$"), datumNabyti, NA)),
         Mdat_trans = format(as.Date(Mdat_ser, origin = "1899-12-30"), "%d.%m.%Y"),
         datnab22 = ifelse(str_detect(datumNabyti, "\\d\\.\\d+\\.\\d+\\."), str_remove(datumNabyti, "\\.$"), Mdat_trans)) %>% 
  relocate(datnab22, .after = datumNabyti) %>% 
  mutate(datvyr64 = str_extract(vyrazeni, "\\d+\\.\\s*\\d+\\.\\s*\\d{4}"),
         dokvyr67 = str_extract(vyrazeni, "MK\\s+\\d+\\/\\d+\\sOM|č.\\s*j.\\s+\\d+\\/\\d+\\sOM|č.\\s*j.\\s+\\d+\\/\\d+.*G|D\\s\\d+\\/\\d+|Kult\\.*\\s\\d+\\/\\d+"),
         dokvyr67 = doklad) %>%  # ktera volba ? 
  relocate(vyrazeni, .before = datvyr64)
  
# az bude potvrzeno, pridat k dd.mm. i rok (z pole 'rok')

# puvod - DOPRACOVAT

dd <- cc %>% 
  mutate(puvmaj28 = ifelse(!is.na(puvod), puvod, ""),
         zpnab23 = case_when(str_detect(zpNabyti,"Dar|dar") ~ "D",
                             str_detect(zpNabyti, "onf") ~ "Konf",
                             str_detect(zpNabyti, "Koup|koup") ~ "K",
                             str_detect(zpNabyti, "nález") ~ "N",
                             str_detect(zpNabyti, "ozůstalost") ~ "Poz",
                             str_detect(zpNabyti, "Sběr|sběr") ~ "Sb",
                             TRUE ~ ""),
         cennab27 = ifelse(str_detect(zpNabyti,"Koup|koup"), str_extract(zpNabyti, "\\d+,-"), "")) %>% 
  relocate(zpNabyti, .before = zpnab23)

# poznamky

ee <- dd %>%
  mutate(pozn20 = paste(ifelse(!is.na(poznamka), paste("poznamka:", poznamka), ""),
                        ifelse(!is.na(poznamkaCZ), paste("poznamkaCZ:", poznamkaCZ), ""),
                                  sep = "\n"),
         nabpozn29 = paste(ifelse(!is.na(zpNabyti), paste("zpNabyti:", zpNabyti), ""),
                           ifelse(!is.na(cenaKR), paste("cenaKR:", cenaKR), ""),
                           ifelse(!is.na(cenaHA), paste("cenaHA:", cenaHA), ""),
                                  sep = "\n"),
         text1_88 = ifelse(!is.na(umisteni), umisteni, ""),
         text2_89 = ifelse(!is.na(umisteniCZ), umisteniCZ, ""))
```

## df20 ok

pro excel 20xx

```{r}

# read 

mysheets <- read_excel_allsheets(paste0(path_kk, "20xx.xlsx")) # specifikuj excel file
df20 <- as.data.frame(rbindlist(mysheets))
names(df20) <- df20[1,] # nacitame bez hlavicky -> nastaveni prvniho radku jako hlavicky
df20 <- df20 %>% filter(is.na(poradi)|poradi!="poradi") # n = 11689 -> vymaze vsechny radky, ktere jsou hlavicky puvodnich listu

# obecne

aa <- df20 %>% 
  mutate(prirc4 = prirc,
         ozn10 = predmet,
         rok12 = rokPK,
         pocetks13 = pocetKs,
         text3_90 = jinecislo)

# prirc - DOPRACOVAT

aa$poradi <- as.numeric(aa$poradi)

bb <- aa %>% 
  mutate(popis11 = popis,
         porc104 = ifelse(!is.na(poradi), poradi, str_extract(prirc, "\\d+")))

# datum nabyti a vyrazeni - DOPRACOVAT

cc <- bb %>% 
  mutate(Mdat_ser = as.numeric(ifelse(str_detect(datumNabyti, "^.....$"), datumNabyti, NA)),
         Mdat_trans = format(as.Date(Mdat_ser, origin = "1899-12-30"), "%d.%m.%Y"),
         Mdat_right = ifelse(str_detect(datumNabyti, "^\\d+\\.\\d+\\.\\d\\d\\d\\d$"), datumNabyti, NA),
         datnab22 = coalesce(Mdat_right, Mdat_trans)) %>% 
  relocate(datnab22, .after = datumNabyti) %>% 
  mutate(vyrdat64 = str_extract(vyrazeni, "\\d{2}\\.\\d+\\.\\d{4}"),
         vyrdok67 = str_extract(vyrazeni, "MK\\s+\\d+\\/\\d+\\sOM|č.j.\\s+\\d+\\/\\d+\\sOM|JCM\\s+\\d+\\/\\d+"))
         
         
check <- cc %>% select(vyrazeni, datvyr64, duvvyr65)
rm(check)
  
# az bude potvrzeno, pridat k dd.mm. i rok (z pole 'rok')

# puvod - DOPRACOVAT

dd <- cc %>% 
  mutate(puvmaj28 = ifelse(!is.na(puvod), puvod, ""),
         predchmaj28 = ifelse(!is.na(puvod), puvod, ""),
         zpnab23 = case_when(str_detect(zpNabyti, "dar|dary|Dar") ~ "D",
                             str_detect(zpNabyti, "Foto") ~ "F",
                             str_detect(zpNabyti, "kopie") ~ "Kp",
                             str_detect(zpNabyti, "koupě|nákup|Nákup") ~ "K",
                             str_detect(zpNabyti, "nález") ~ "N",
                             str_detect(zpNabyti, "odevzdaný nález") ~ "On",
                             str_detect(zpNabyti, "preparace") ~ "Pr",
                             str_detect(zpNabyti, "převod|Převod") ~ "P",
                             str_detect(zpNabyti, "sběr|Sběr") ~ "S",
                             str_detect(zpNabyti, "staré fondy") ~ "SF",
                             str_detect(zpNabyti, "výzkum|Průzkum") ~ "V",
                             str_detect(zpNabyti, "vlastní činnost") ~ "VC",
                             TRUE ~ NA))

# poznamky

ee <- dd %>%
  mutate(pozn20 = paste(ifelse(!is.na(poznamka), paste("poznamka:", poznamka), ""),
                           ifelse(!is.na(poznamkaCZ), paste("poznamkaCZ:", poznamkaCZ), ""),
                                  sep = "\n"),
         nabpozn29 = paste(ifelse(!is.na(cenaKR), paste("cenaKR:", cenaKR), ""),
                           ifelse(!is.na(cenaHA), paste("cenaHA:", cenaHA), ""),
                                  sep = "\n"),
         text1_88 = ifelse(!is.na(umisteni), umisteni, ""),
         text2_89 = ifelse(!is.na(umisteniCZ), umisteniCZ, ""))

```

# CSV

```{r}

Lpk <- c("sbirka1", "podsb2", "cisrada3", "prirc4", "invc5", "lok6"," prirpla7", "prirpla8", "prirpla9", "ozn10",
         "popis11", "rok12", "pocetks13", "obal14", "evid15", "mater16", "datace17", "stav18", "popstav19", "pozn20",
         "liter21", "datnab22", "zpnab23", "typ24","doklnab25", "mena26", "cennab27", "puvmaj28", "nabpozn29", "typ30",
         "armisto31", "arkontext32", "arakce33", "arvyzk34", "arlok35", "arku36", "arparc37", "arpoz38", "nalpozn39", "naladr40",
         "nalokr41", "nalobec42", "nalcast43", "nalmc44", "nalcis45", "nalul46", "nalorc47", "nalpsc48", "stat49", "artext50",
         "polpop51", "polCES52", "polks53", "poldopl1_54", " poldopl1_55", "poldopl2_56", "poldopl2_57", "poldopl3_58", "poldopl3_59", "archiv60",
         "acvsign61", "acvmark62", "acvpozn63", "vyrdat64", "vyrduv65", "vyrtyp66", "vyrdok67", "vyrmena68", "vyrcena69", "zpub70",
         "vyrCES71", "novaj72", "poznvyr73", "predchmaj74", "userins75", "datins76", "arkontext2_77", "arkontext3_78", "arkomp79", "arSJTSK80",
         "arcizivyz81", "arnazevvyz82", "arrokvyz83", "arfirmavyz84", "arvedoucivyz85", "rokakvi86", "prisp87", 
         "text1_88", "text2_89", "text3_90", "text4_91", "text5_92", 
         "priz1_93", "priz2_94", "priz3_95", "priz4_96", "priz5_97", 
         "datzap98", "text6_99", "text7_100", "text8_101", "text9_102", "text10_103", "porc104", "subc105") # 105
         
# uprav dle excelu, ktery zpracovavas

# n <- 2521
# imp <- "df18"

n <- 3428
imp <- "df19"
   
mus_tab <- data.frame(smazme = 1:n)

for(i in Lpk){
  if(i %in% colnames(ee)){
    ano <- ee %>% select(all_of(i))
    mus_tab <- cbind(mus_tab, ano)
    print("jo")
  } else{
    ne <- data.frame(rep(NA, n))
    colnames(ne) <- i
    mus_tab <- cbind(mus_tab, ne)
    print("houby")}
}

mus_tab <- mus_tab %>% select(-smazme)

# SAVE

f2s <- paste0(path_kk, proj, "_import_", imp, ".csv")

if(file.exists(f2s)){
  print("You've been here before!")
  rm(f2s)
} else {
  write.table(mus_tab, file = f2s,
            quote = T, row.names = F, 
            sep = ";", dec = ",", 
            na = "", fileEncoding="cp1250")
  print("Import csv  W R I T T E N  !")
  rm(f2s)
}


```
# A C T U A L ---------------------

df53 df68 df80 df20 -> sloucit


## load

```{r}

# df53
mysheets <- read_excel_allsheets(paste0(path_kk, "1953-1979.xlsx"))
df53 <- as.data.frame(rbindlist(mysheets, fill = T))
names(df53) <- df53[1,]
names(df53)[16] = "xpozn"
df53 <- df53 %>% filter(is.na(rokPK)|rokPK!="rokPK") %>% # n = 27579 
    mutate(osoba = "")
df53$rokPK <- as.numeric(df53$rokPK) 
df53 <- df53 %>% filter(rokPK %in% 1953:1967) %>% # filtr roku
    mutate(osoba = "", poradi = "")
# df68
df68 <- readxl::read_excel(paste0(path_proj, "68-79.xlsx"), sheet = 1, col_types = "text") %>% mutate(osoba = "", poradi = "")

# df80
df80 <- readxl::read_excel(paste0(path_proj, "80-99.xlsx"), sheet = 1, col_types = "text") %>% 
  mutate(osoba = ziskal, datumNabyti = datunNabyti, poradi = "", Sign = Sign.) 
  # filter(prirc != "Číslo přír.")

# df20
mysheets <- read_excel_allsheets(paste0(path_kk, "20xx.xlsx")) # specifikuj excel file
df20 <- as.data.frame(rbindlist(mysheets))
names(df20) <- df20[1,] # nacitame bez hlavicky -> nastaveni prvniho radku jako hlavicky
df20 <- df20 %>% filter(is.na(poradi)|poradi!="poradi") %>% # n = 11689 -> vymaze vsechny radky, ktere jsou hlavicky puvodnich listu
    mutate(Revize = revize,
           rokPK = ifelse(rokPK == "20021", "2001", rokPK))

# rbind

sel53 <- df53 %>% select(poradi, prirc, rokPK, datumNabyti, Sign, invc, predmet, popis, pocetKs, zpNabyti, doklad, puvod, vyrazeni, Revize, podsbirka, jinecislo, osoba)
sel68 <- df68 %>% select(poradi, prirc, rokPK, datumNabyti, Sign, invc, predmet, popis, pocetKs, zpNabyti, doklad, puvod, vyrazeni, Revize, podsbirka, jinecislo, osoba)
sel80 <- df80 %>% select(poradi, prirc, rokPK, datumNabyti, Sign, invc, predmet, popis, pocetKs, zpNabyti, doklad, puvod, vyrazeni, Revize, podsbirka, jinecislo, osoba)
sel20 <- df20 %>% select(poradi, prirc, rokPK, datumNabyti, Sign, invc, predmet, popis, pocetKs, zpNabyti, doklad, puvod, vyrazeni, Revize, podsbirka, jinecislo, osoba)

later <- rbind(sel53, sel68, sel80, sel20)

nrow(later) == nrow(sel53) + nrow(sel68) + nrow(sel80) + nrow(sel20) # TRUE
```
## obdobi a masky

```{r}

vednul <- later %>% 
  group_by(rokPK) %>% 
  summarise(maxcislo = max(prirc))

vednul <- aa %>% 
  mutate(porc104 = as.numeric(porc104)) %>% 
  group_by(rokPK) %>% 
  summarise(maxcislo = max(na.omit(porc104)))

write.table(vednul, "clipboard", sep = "\t", row.names = FALSE)

```

## proces

```{r}

aa <- later %>% 
  mutate(porc104 = ifelse(str_detect(prirc, "Z"), str_extract(prirc, "\\d+"), prirc)) %>% relocate(porc104, .after = poradi) %>% 
  mutate(prirc4 = case_when(rokPK %in% c("1956", "1958", "1959", "1960", "1965", "1966", 
                                         "1972", "1973", "1974", "1975", "1977", "1978",
                                         "1980", "1983") ~ paste0(str_pad(porc104, 4, pad = "0"), "/", rokPK),
                            TRUE ~ paste0(str_pad(porc104, 3, pad = "0"), "/", rokPK))) %>% 
  relocate(prirc4, .after = prirc) %>% 
  mutate(rok12 = rokPK) %>% relocate(rok12, .after = rokPK) %>% 
  mutate(Mdat_ser = as.numeric(ifelse(str_detect(datumNabyti, "^.....$"), datumNabyti, NA)),
         Mdat_trans = format(as.Date(Mdat_ser, origin = "1899-12-30"), "%d.%m.%Y"),
         datnab22 = ifelse(str_detect(datumNabyti, "^.....$"), Mdat_trans, 
                           ifelse(str_detect(datumNabyti, "\\."), sub("\\.$", "", datumNabyti), datumNabyti))) %>% 
  relocate(datnab22, .after = datumNabyti) %>% 
  # Sign ?
  # invc ?
  mutate(ozn10 = predmet) %>% relocate(ozn10, .after = predmet) %>% 
  mutate(popis11 = popis) %>% relocate(popis11, .after = popis) %>% 
  mutate(pocetks13 = pocetKs) %>% relocate(pocetks13, .after = pocetKs) %>% 
  mutate(zpnab23 = case_when(str_detect(zpNabyti, "(?i)koup|nákup") ~ "K",
                             str_detect(zpNabyti, "Koupí od dědiců") ~ "B",
                             str_detect(zpNabyti, "(?i)dar") ~ "D",
                             str_detect(zpNabyti, "(?i)konf") & !str_detect(zpNabyti, "(?i)koup") ~ "F",
                             str_detect(zpNabyti, "(?i)nalez|nález") ~ "N",
                             str_detect(zpNabyti, "(?i)odkaz") ~ "O",
                             str_detect(zpNabyti, "(?i)převod") ~ "P",
                             str_detect(zpNabyti, "(?i)star.*fond") ~ "S",
                             str_detect(zpNabyti, "(?i)pozůst") ~ "T",
                             str_detect(zpNabyti, "(?i)výzkum") ~ "V",
                             TRUE ~ NA)) %>% relocate(zpnab23, .after = zpNabyti) %>% # zpNabyti take do poznnab29
  mutate(doklnab25 = doklad) %>% relocate(doklnab25, .after = doklad) %>% 
  mutate(puvmaj28 = puvod) %>% relocate(puvmaj28, .after = puvod) %>% 
  mutate(vyrdat64 = str_extract(vyrazeni, "\\d+\\.\\s*\\d+\\.\\s*\\d{4}"),
         vyrdok67 = str_extract(vyrazeni, "MK\\s*\\d+\\/\\d+|č.\\s*j.\\s*\\d+\\/\\d+|č.\\s*j.\\s*\\d+\\/\\d+|D\\s\\d+\\/\\d+|Kult\\.*\\s\\d+\\/\\d+|MK\\s*\\d+\\/\\d+\\sOM|č.\\s*j.\\s*\\d+\\/\\d+\\sOM|č.\\s*j.\\s*\\d+\\/\\d+.*G|D\\s\\d+\\/\\d+|Kult\\.*\\s\\d+\\/\\d+|č\\.*\\s*j\\.\\s*\\w+\\s*\\d+\\/\\d+")) %>% 
  relocate(vyrdok67, .after = vyrazeni) %>% 
  relocate(vyrdat64, .after = vyrazeni) %>% # vyrazeni take do pozvyr73
  mutate(text4_91 = Revize) %>% relocate(text4_91, .after = Revize) %>% 
  mutate(podsb2 = ifelse(!is.na(podsbirka), ifelse(str_detect(podsbirka, "^\\d+$"), podsbirka, "99"), NA)) %>% relocate(podsb2, .after = podsbirka) %>% # ostatni udaje (sporne podsb. atd) do pozn20
  mutate(text3_90 = jinecislo) %>% relocate(text3_90, .after = jinecislo) %>%
  mutate(pozn20 = ifelse(!is.na(podsbirka), paste("podsbirka:", podsbirka), NA)) %>% relocate(pozn20, .after = podsb2) %>% 
  mutate(nabpozn29 = ifelse(!is.na(zpNabyti), paste("zpNabyti: ", zpNabyti), NA),
         poznvyr73 = ifelse(!is.na(vyrazeni), paste("vyrazeni: ", vyrazeni), NA))
 
  
rndm <- sample(later$datumNabyti, size = 10, replace = F)
rndm
```



# --- not actual


```{r}

# coltypes

df$datum <- ifelse(str_detect(df$datum, "\\d+\\/\\d+\\s....$"), gsub("\\/|\\s", ".", df$datum) , df$datum) 
df$datum <- ifelse(str_detect(df$datum, "\\d+\\/\\d+"), gsub("\\/", ".", df$datum) , df$datum) 
df$datum <- ifelse(str_detect(df$datum, "\\sbis\\s"), df$datum, gsub("\\s", "", df$datum)) 
df$datum <- ifelse(str_detect(df$datum, "^\\d+\\.\\d+$"), paste0(df$datum, "."), df$datum) 

library(anytime) 
df$datum <- anydate(df$datum) # nic moc

# format(as.Date(df$datum, format="%d/%m/%Y"), "%d/%m/%y")

```

# --- 1st round
## EDA

```{r}

Lxls <- list.files(path_data, pattern = "*.xlsx")  # Identify file names

Lxls <- "M:/03 klienti/kraj jihocesky/jihoceske muzeum v ceskych budejovicich - JMCB/03 migrace/jmcb migrace 2023/zdrojdat/1916.xlsx"

eda <- data.frame()

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

for(i in Lxls) {
  a <- read_excel(paste0(path_data, i),
              sheet = 1, col_names=FALSE,
              range = cell_cols("A:P")) %>% 
       slice(2)
  a$zdroj <- paste(i) # add source txt file name
  # print(count(a))
  eda <- rbind(eda, a)
  print(i)
  # rm(a)
}

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

a <- read_excel("M:/03 klienti/kraj jihocesky/jihoceske muzeum v ceskych budejovicich - JMCB/03 migrace/jmcb migrace 2023/zdrojdat/1916.xlsx",
              sheet = 1, col_names=FALSE)
       #        range = cell_cols("A:P")) %>% 
       # slice(2)

```

## LOAD CES TXT LOOP

```{r LOAD CES TXT LOOP , warning = F}

df_filled <- data.frame()

colnam <- c("prirc","rok_prir","dat_nabyt", "sign","invc", 
            "predmet",  "char_pop", "pocet_ks", "zp_nabyt", "doklad",
            "puvod_ptu","odp","rok_reviz","podsb", "jinec", "pozn_okr") # n = 16


# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

for(i in Lxls) { # Lxls from EDA
  a <- readxl::read_xlsx(paste0(path_data, i),
              sheet = 1,
              skip = 1,
              col_types = c("text")) # nefuguje -> prevadi na datum vsechna pole
              # col_types = c("text", "text", "date", "text","text",
              #               "text", "text", "text", "text", "text", 
              #               "text", "text", "text", "text", "text"))
  # names(a) <- colnam
  a$zdroj <- paste(i) # add source txt file name
  # print(count(a))
  # df_filled <- rbind(df_filled, a)
 
  df_filled <- bind_rows(df_filled, a)
  print(i)
  # rm(a)
}

df_filled$`Datum nabytí` <- as.Date.character(df_filled$`Datum nabytí`) 

# install.packages("anytime")   # Install anytime package
# library("anytime") 
# df_filled$`Datum nabytí` <- anydate(df_filled$`Datum nabytí`) # nope


# ? kdyz vyuziju skip = 1, nacita se datum ve spravnem formatu, ale nejsem schopna nacist sloupce A:P
# ? kdyz vyuziju cell_colls, nefunguje skip a datum se nacita blbe

install.packages("XLConnect")
require(XLConnect)

for(i in Lxls) {
  a <- readxl::read_excel(paste0(path_data, i),
              sheet = 1,
              skip = 1) 
              # col_types = c("text"))
  # names(a) <- colnam
  a$zdroj <- paste(i) # add source txt file name
  # print(count(a))
  df_filled <- bind_rows(df_filled, a)
  print(i)
  # rm(a)
}

a <- readxl::read_excel(paste0(path_data, "1987 (Z).xlsx"),
              sheet = 1,
              skip = 1,
              col_types = c("text", "text", "date", "text","text",
                            "text", "text", "text", "text", "text", 
                            "text", "text", "text", "text", "text")) 

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# CHECK AND CLEAR ENVIRONMENT

print(count(df_filled))
rm(i)
rm(colnam)
rm(Lxls)


# SAVE COMBINED XLS


f2s <- paste0(path_kk, proj, "_allXLSX.csv")

if(file.exists(f2s)){
  print("You've been here before.")
  rm(f2s)
} else {
  write.table(df_filled, file = f2s, 
            quote = T, row.names = F, 
            sep = ";", dec = ",", 
            na = "", fileEncoding="cp1250")
  rm(f2s)
  print("File saved!")
  }

# rm(df_filled)
# 
```

..
()

